### PR TITLE
Jb spainlayout

### PR DESCRIPTION
**Pull request by joelbeckum**
To test, run serve in terminal to initiate json server, then navigate to spain.html from placeholder link on the landing page.

### CODE REVIEW

**Review by IanJames2 — COMMENTED** [review]
Give me one sec lol

**Review by auntviv — APPROVED** [review]
This looks good!

**Review by auntviv — APPROVED** [review]
Simple clean change

**Review by IanJames2 — APPROVED** [review]
Good to go...

**Pull request merged**
